name: Build
run-name: Build and test of commit "${{ github.event.head_commit.message }}"

on:
  push:
    branches:
      - "*"

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        platesolving: ['with platesolving', 'without platesolving']

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: |
        cmake -B ${{ steps.strings.outputs.build-output-dir }} \
          -DASTROPHOTOTOOLBOX_INCLUDE_PLATESOLVING=${{ matrix.platesolving == 'with platesolving' }} \
          -DASTROPHOTOTOOLBOX_RUN_TESTS=OFF \
          -DENABLE_OPENMP=OFF \
          -DCMAKE_BUILD_TYPE=Release \
          -S ${{ github.workspace }}

    - name: Build
      run: |
        cmake --build ${{ steps.strings.outputs.build-output-dir }}

    - name: Run unit tests
      run: |
        rm -rf ${{ steps.strings.outputs.build-output-dir }}/tests/tmp/
        mkdir -p ${{ steps.strings.outputs.build-output-dir }}/tests/tmp/empty
        ${{ steps.strings.outputs.build-output-dir }}/bin/unittests
